name: bug-fix
description: "Workflow для исправления багов с использованием LangGraph"

stages:
  - name: analyze_bug
    agent: developer-basic
    user_prompt: "Проанализируй этот баг и воспроизведи проблему"
    skippable: false
    description: "Анализ бага и воспроизведение проблемы"
    human_input_required: true
    human_input_prompt: "Опишите детали бага и шаги для воспроизведения"
  
  - name: investigate_root_cause
    agent: developer-advanced
    user_prompt: "Найди первопричину бага в коде, проведи глубокий анализ"
    skippable: false
    description: "Поиск первопричины бага в коде"
    depends_on: [analyze_bug]
  
  - name: design_fix
    agent: developer-advanced
    user_prompt: "Спроектируй решение для исправления, учитывая архитектуру системы"
    skippable: false
    description: "Проектирование решения для исправления"
    depends_on: [investigate_root_cause]
  
  - name: implement_fix
    agent: developer-basic
    user_prompt: "Реализуй исправление согласно проекту"
    skippable: false
    description: "Реализация исправления"
    depends_on: [design_fix]
  
  - name: create_regression_tests
    agent: tester-basic
    user_prompt: "Создай тесты для предотвращения повторения этого бага"
    skippable: false
    description: "Создание тестов для предотвращения повторения бага"
    depends_on: [implement_fix]
  
  - name: verify_fix
    agent: tester-basic
    user_prompt: "Проверь исправление и запусти все тесты"
    skippable: false
    description: "Проверка исправления и запуск тестов"
    depends_on: [create_regression_tests]
  
  - name: code_review
    agent: developer-advanced
    user_prompt: "Проведи код-ревью исправления, проверь качество и соответствие стандартам"
    skippable: true
    description: "Код-ревью исправления"
    depends_on: [verify_fix]
    human_approval_required: true

# Условные переходы
conditional_flows:
  - from: verify_fix
    condition: "fix_verification_failed"
    true_path: investigate_root_cause  # Возврат к анализу
    false_path: code_review  # Продолжение к ревью

# Настройки workflow
settings:
  max_retries: 2
  timeout_minutes: 60
  checkpoint_frequency: "after_each_stage"
  
  human_approval_required:
    - code_review
  
  notifications:
    on_completion: true
    on_failure: true
    on_human_input_required: true
  
  # Автоматическое создание отчета
  auto_report:
    enabled: true
    include_sections:
      - bug_description
      - root_cause_analysis
      - fix_implementation
      - test_results
      - verification_status
